const jobs = [
  {
    organization: "Aquent",
    link: "https://aquent.com/",
    position: "Front End React Developer",
    timeOfApplication: "1681792644852",
    response: false,
    firstInterview: false,
    secondInterview: false,
    thirdInterview: false,
    hired: false,
  },
  //   {
  //     title: "",
  //     link: "",
  //     position: "",
  //     timeOfApplication: "",
  //     response: false,
  //     firstInterview: false,
  //     secondInterview: false,
  //     thirdInterview: false,
  //     hired: false,
  //   },
  //   {
  //     title: "",
  //     link: "",
  //     position: "",
  //     timeOfApplication: "",
  //     response: false,
  //     firstInterview: false,
  //     secondInterview: false,
  //     thirdInterview: false,
  //     hired: false,
  //   },
];
export default { jobs };
