const jobs = [
  {
    org: "Aquent",
    link: "https://aquent.com/",
    posting:
      "https://www.linkedin.com/jobs/search/?currentJobId=3542402198&f_E=1%2C2&geoId=103644278&keywords=austin%20junior%20developer%20react&location=United%20States&refresh=true",
    position: "Front End React Developer",
    time: 1681792644852,
    catered: "no",
    response: false,
    firstInterview: false,
    secondInterview: false,
    thirdInterview: false,
    hired: false,
    middleMan: "linkedin",
    message: "",
    reference: "",
    remote: true,
    available: false,
  },
  {
    org: "Lancesoft",
    link: "https://www.lancesoft.com/aboutus.php",
    posting:
      "https://www2.jobdiva.com/portal/?a=3djdnw5yqdh8wl3frr5t6561tvvokq01affwpxt3lcutzo4f8yt1aeiy3msk02or&compid=0#/jobs/18837729",
    position: "Web Developer",
    time: 1681806880138,
    catered: "somewhat",
    response: false,
    firstInterview: false,
    secondInterview: false,
    thirdInterview: false,
    hired: false,
    middleMan: "linkedin",
    message: `Greetings, Lancesoft, my name is Toby Van Baast and I'm a Web Developer from Austin. Your add on LinkedIn caught my interest.
Currently, I have been visiting family in Perth, Australia. I'll return to Austin, April 30th with an American phone number.

I have had a singular focus on learning Web Development and building projects the past 2 years, and around 5 years on and off. Some of that experience is with Python and Django; however, most of my experience is Javascript and React.

Looking at your website really resonated with me, the design language just makes sense and the message is clear and practical. 
I also enjoyed the 4 Ps.
Here are mine.
Purpose:
My purpose is to learn and put into practice what should be prioritized in order to be effective and resourceful.
People:
I strive to practice appreciation, and to realize value in others and the environment.
Performance:
I greatly appreciate quick and frequent feedback of my actions. This serves as great help in recognizing patterns and developing an awareness of effective actions.
Partnerships:
Maintaining relationships through the seasons, improves trust, loyalty, and sense of familiarity. Community makes us all accountable.

I would be absolutely pleased to work with you.
Here is my portfolio: https://portfolio-90faf.web.app/`,
    reference: "",
    remote: false,
    available: true,
  },
  {
    org: "Accruent",
    link: "https://www.accruent.com/",
    posting: "https://boards.greenhouse.io/accruenthq/jobs/3440011?t=708ijw1",
    position: "Support Agent",
    time: 1681821075938,
    catered: "no",
    response: false,
    firstInterview: false,
    secondInterview: false,
    thirdInterview: false,
    hired: false,
    middleMan: "linkedin",
    message: "",
    reference: "Greg Van Baast, (Dad)",
    remote: true,
    available: true,
  },
  {
    org: "Eagle Eye Networks",
    link: "https://www.een.com/",
    posting:
      "https://www.indeed.com/jobs?q=junior+developer&l=Austin%2C+TX&vjk=045d342891720ad7",
    position: "Junior Software Engineer - On Site",
    time: 1681912571743,
    catered: "no",
    response: false,
    firstInterview: false,
    secondInterview: false,
    thirdInterview: false,
    hired: false,
    middleMan: "indeed",
    message: "",
    reference: "",
    remote: true,
    available: true,
  },
  {
    org: "Actum Labs",
    link: "https://actumlab.com/",
    posting: "https://actumlab.com/junior-backend-developer/",
    position: "Junior Backend Developer",
    time: 1681916522007,
    catered: "no",
    response: false,
    firstInterview: false,
    secondInterview: false,
    thirdInterview: false,
    hired: false,
    middleMan: "indeed",
    message: "",
    reference: "",
    remote: true,
    available: true,
  },
  {
    org: "Intertech, Inc",
    link: "https://www.intertech.com/",
    posting:
      "https://www.indeed.com/viewjob?from=app-tracker-post_apply-appcard&hl=en&jk=9aab0c65480c9983&tk=1gufdoeemqoer800",
    position: "Part-time Coding and Abacus Teacher",
    time: 1681997783150,
    catered: "no",
    response: false,
    firstInterview: false,
    secondInterview: false,
    thirdInterview: false,
    hired: false,
    middleMan: "indeed",
    message: "",
    reference: "",
    remote: true,
    available: true,
  },
  {
    org: "Challenger School Foundation",
    link: "https://www.challengerschool.com/",
    posting:
      "https://www.indeed.com/viewjob?from=app-tracker-post_apply-appcard&hl=en&jk=2ccc22725b8331c4&tk=1gufdoeemqoer800",
    position: "Computer Science Teacher",
    time: 1681997783150,
    catered: "no",
    response: false,
    firstInterview: false,
    secondInterview: false,
    thirdInterview: false,
    hired: false,
    middleMan: "indeed",
    message: "",
    reference: "",
    remote: false,
    available: true,
  },
  {
    org: "Best Brains of Austin - Southwest",
    link: "https://www.bestbrainsaveryranch.com/",
    posting:
      "https://www.indeed.com/viewjob?from=app-tracker-post_apply-appcard&hl=en&jk=1bab0366da9f7653&tk=1gufdoeemqoer800",
    position: "Part-time Coding and Abacus Teacher",
    time: 1681997783150,
    catered: "no",
    response: false,
    firstInterview: false,
    secondInterview: false,
    thirdInterview: false,
    hired: false,
    middleMan: "indeed",
    message: "",
    reference: "",
    remote: false,
    available: true,
  },
  //     {
  //   org: "",
  //   link: "",
  //   posting: "",
  //   position: "",
  //   time: ,
  //   catered: "no",
  //   response: false,
  //   firstInterview: false,
  //   secondInterview: false,
  //   thirdInterview: false,
  //   hired: false,
  //   middleMan: false,
  //     message: "",
  //   reference:"",
  // remote:true,
  // available:true,
  // },
];
export default { jobs };
